# Generated by Django 3.0 on 2022-04-11 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=40)),
                ('build_address', models.TextField(max_length=400)),
                ('region', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('point_of_contact', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=40)),
                ('is_status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('building_grp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructedby', to='building.BuildingGroup')),
            ],
        ),
    ]
